// Email Report Delivery

import type { ReportMetadata } from '@/lib/reports/types';

/**
 * Send report via email
 * Note: Integrate with your email service (SendGrid, Resend, etc.)
 */
export async function emailReport(
  recipients: string[],
  report: Buffer,
  metadata: ReportMetadata
): Promise<{ success: boolean; error?: string }> {
  try {
    // Validate recipients
    const validRecipients = recipients.filter(isValidEmail);

    if (validRecipients.length === 0) {
      throw new Error('No valid email recipients');
    }

    // Generate email content (prepared for email service integration)
    void generateEmailHTML(metadata);
    void generateEmailText(metadata);

    // TODO: Integrate with email service
    // Example with Resend:
    /*
    const { Resend } = await import('resend');
    const resend = new Resend(process.env['RESEND_API_KEY']);

    await resend.emails.send({
      from: 'reports@chronos.app',
      to: validRecipients,
      subject: `${metadata.title} - ${metadata.dateRange.start} to ${metadata.dateRange.end}`,
      html: emailHTML,
      text: emailText,
      attachments: [
        {
          filename: `${sanitizeFilename(metadata.title)}.pdf`,
          content: report,
        },
      ],
    });
    */

    // For now, log the email attempt
    console.log('Email would be sent to:', validRecipients);
    console.log('Report metadata:', metadata);
    console.log('Report size:', report.length, 'bytes');

    return { success: true };
  } catch (error) {
    console.error('Failed to send email report:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Generate HTML email template
 */
function generateEmailHTML(metadata: ReportMetadata): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${metadata.title}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; margin: 0; padding: 0; background-color: #f3f4f6;">
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <!-- Header -->
    <tr>
      <td style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 40px 20px; text-align: center;">
        <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700;">
          ${metadata.title}
        </h1>
        <p style="margin: 10px 0 0; color: #e0e7ff; font-size: 16px;">
          ${metadata.dateRange.start} - ${metadata.dateRange.end}
        </p>
      </td>
    </tr>

    <!-- Content -->
    <tr>
      <td style="padding: 40px 30px;">
        <p style="margin: 0 0 20px; color: #374151; font-size: 16px; line-height: 1.6;">
          Your scheduled analytics report is ready! Please find the detailed PDF report attached to this email.
        </p>

        <div style="background-color: #f9fafb; border-left: 4px solid #6366f1; padding: 20px; margin: 30px 0; border-radius: 4px;">
          <h2 style="margin: 0 0 15px; color: #1f2937; font-size: 18px; font-weight: 600;">
            Report Details
          </h2>
          <ul style="margin: 0; padding-left: 20px; color: #4b5563;">
            <li style="margin-bottom: 8px;">Generated: ${new Date(metadata.generatedAt).toLocaleString()}</li>
            ${metadata.companyName ? `<li style="margin-bottom: 8px;">Company: ${metadata.companyName}</li>` : ''}
            ${metadata.creatorName ? `<li style="margin-bottom: 8px;">Creator: ${metadata.creatorName}</li>` : ''}
          </ul>
        </div>

        <p style="margin: 30px 0 0; color: #6b7280; font-size: 14px; line-height: 1.6;">
          This report was automatically generated by Chronos Analytics. To manage your report settings or schedule, please visit your dashboard.
        </p>
      </td>
    </tr>

    <!-- CTA -->
    <tr>
      <td style="padding: 0 30px 40px;">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td align="center">
              <a href="https://chronos.app/dashboard" style="display: inline-block; background: linear-gradient(135deg, #6366f1, #8b5cf6); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 6px; font-weight: 600; font-size: 16px;">
                View Dashboard
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- Footer -->
    <tr>
      <td style="background-color: #f9fafb; padding: 30px; text-align: center; border-top: 1px solid #e5e7eb;">
        <p style="margin: 0 0 10px; color: #6b7280; font-size: 14px;">
          Chronos Analytics - Powered by Whop
        </p>
        <p style="margin: 0; color: #9ca3af; font-size: 12px;">
          This is an automated email. Please do not reply.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

/**
 * Generate plain text email
 */
function generateEmailText(metadata: ReportMetadata): string {
  return `
${metadata.title}
${metadata.dateRange.start} - ${metadata.dateRange.end}

Your scheduled analytics report is ready!

Report Details:
- Generated: ${new Date(metadata.generatedAt).toLocaleString()}
${metadata.companyName ? `- Company: ${metadata.companyName}` : ''}
${metadata.creatorName ? `- Creator: ${metadata.creatorName}` : ''}

Please find the detailed PDF report attached to this email.

This report was automatically generated by Chronos Analytics.

View Dashboard: https://chronos.app/dashboard

---
Chronos Analytics - Powered by Whop
This is an automated email. Please do not reply.
  `.trim();
}

/**
 * Validate email address
 */
function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

/**
 * Sanitize filename for attachment
 * TODO: Uncomment when email service is integrated
 */
/*
function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-z0-9_\-]/gi, '_')
    .replace(/_{2,}/g, '_')
    .toLowerCase();
}
*/

/**
 * Track email delivery status
 */
export async function trackEmailDelivery(
  reportHistoryId: string,
  status: 'sent' | 'failed',
  error?: string
): Promise<void> {
  try {
    // TODO: Update report_history table with delivery status
    console.log('Email delivery tracked:', {
      reportHistoryId,
      status,
      error,
      timestamp: new Date().toISOString(),
    });
  } catch (err) {
    console.error('Failed to track email delivery:', err);
  }
}
