-- Migration: Add chat analytics columns to chat_messages table
-- Created: 2025-01-10
-- Description: Add columns for tracking AI usage metrics, cost, and video references

-- Add analytics columns to chat_messages table
ALTER TABLE chat_messages
ADD COLUMN IF NOT EXISTS input_tokens INTEGER,
ADD COLUMN IF NOT EXISTS output_tokens INTEGER,
ADD COLUMN IF NOT EXISTS model VARCHAR(50) DEFAULT 'claude-3-5-haiku-20241022',
ADD COLUMN IF NOT EXISTS cost_usd DECIMAL(10, 6),
ADD COLUMN IF NOT EXISTS response_time_ms INTEGER,
ADD COLUMN IF NOT EXISTS has_video_reference BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS video_references TEXT[];

-- Add comments for documentation
COMMENT ON COLUMN chat_messages.input_tokens IS 'Number of input tokens sent to AI model';
COMMENT ON COLUMN chat_messages.output_tokens IS 'Number of output tokens generated by AI model';
COMMENT ON COLUMN chat_messages.model IS 'AI model used for this response (e.g., claude-3-5-haiku-20241022)';
COMMENT ON COLUMN chat_messages.cost_usd IS 'Cost in USD for this AI API call';
COMMENT ON COLUMN chat_messages.response_time_ms IS 'Time taken to generate response in milliseconds';
COMMENT ON COLUMN chat_messages.has_video_reference IS 'Whether this message contains video references/citations';
COMMENT ON COLUMN chat_messages.video_references IS 'Array of video IDs referenced in this message';

-- Create indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_chat_messages_creator_date
ON chat_messages(creator_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_student_session
ON chat_messages(student_id, session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_chat_messages_role_creator
ON chat_messages(role, creator_id)
WHERE role = 'assistant';

CREATE INDEX IF NOT EXISTS idx_chat_messages_video_refs
ON chat_messages USING GIN(video_references)
WHERE video_references IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chat_messages_cost
ON chat_messages(creator_id, created_at DESC, cost_usd)
WHERE cost_usd IS NOT NULL;

-- Add check constraint for valid roles
ALTER TABLE chat_messages
ADD CONSTRAINT check_message_role
CHECK (role IN ('user', 'assistant', 'system'));

-- Add check constraint for non-negative tokens
ALTER TABLE chat_messages
ADD CONSTRAINT check_tokens_positive
CHECK (
  (input_tokens IS NULL OR input_tokens >= 0) AND
  (output_tokens IS NULL OR output_tokens >= 0)
);

-- Add check constraint for non-negative cost
ALTER TABLE chat_messages
ADD CONSTRAINT check_cost_positive
CHECK (cost_usd IS NULL OR cost_usd >= 0);

-- Add check constraint for non-negative response time
ALTER TABLE chat_messages
ADD CONSTRAINT check_response_time_positive
CHECK (response_time_ms IS NULL OR response_time_ms >= 0);

-- Create function to automatically set has_video_reference
CREATE OR REPLACE FUNCTION update_has_video_reference()
RETURNS TRIGGER AS $$
BEGIN
  NEW.has_video_reference := (NEW.video_references IS NOT NULL AND array_length(NEW.video_references, 1) > 0);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update has_video_reference
DROP TRIGGER IF EXISTS trigger_update_has_video_reference ON chat_messages;
CREATE TRIGGER trigger_update_has_video_reference
BEFORE INSERT OR UPDATE OF video_references ON chat_messages
FOR EACH ROW
EXECUTE FUNCTION update_has_video_reference();

-- Create view for easy cost analytics queries
CREATE OR REPLACE VIEW chat_cost_analytics AS
SELECT
  creator_id,
  DATE(created_at) as date,
  model,
  COUNT(*) as message_count,
  SUM(input_tokens) as total_input_tokens,
  SUM(output_tokens) as total_output_tokens,
  SUM(cost_usd) as total_cost,
  AVG(cost_usd) as avg_cost_per_message,
  AVG(response_time_ms) as avg_response_time_ms
FROM chat_messages
WHERE role = 'assistant' AND cost_usd IS NOT NULL
GROUP BY creator_id, DATE(created_at), model
ORDER BY creator_id, date DESC, model;

-- Grant permissions (adjust as needed for your RLS policies)
GRANT SELECT ON chat_cost_analytics TO authenticated;

-- Create view for session analytics
CREATE OR REPLACE VIEW chat_session_analytics AS
SELECT
  session_id,
  creator_id,
  student_id,
  COUNT(*) as message_count,
  MIN(created_at) as session_start,
  MAX(created_at) as session_end,
  EXTRACT(EPOCH FROM (MAX(created_at) - MIN(created_at))) as duration_seconds,
  COUNT(CASE WHEN role = 'user' THEN 1 END) as user_messages,
  COUNT(CASE WHEN role = 'assistant' THEN 1 END) as ai_messages,
  SUM(CASE WHEN role = 'assistant' THEN cost_usd ELSE 0 END) as session_cost,
  AVG(CASE WHEN role = 'assistant' THEN response_time_ms END) as avg_response_time_ms,
  BOOL_OR(has_video_reference) as has_video_references
FROM chat_messages
WHERE session_id IS NOT NULL
GROUP BY session_id, creator_id, student_id
ORDER BY session_start DESC;

-- Grant permissions
GRANT SELECT ON chat_session_analytics TO authenticated;

-- Add helpful comments
COMMENT ON VIEW chat_cost_analytics IS 'Aggregated daily cost metrics by creator and model';
COMMENT ON VIEW chat_session_analytics IS 'Session-level analytics including duration, cost, and message counts';
